#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Feel free to change the data structures generated by AI.

#define MAX_SYSCALLS 1024
#define TOP_N 5

typedef struct {
    char name[64];
    double time;
} syscall_stat;

typedef struct {
    syscall_stat stats[MAX_SYSCALLS];
    int count;
    double total_time;
} syscall_stats;

int parse_strace_line(char *line, char *syscall_name, double *time) {
}

void add_syscall(syscall_stats *stats, const char *name, double time) {
}

void print_top_syscalls(syscall_stats *stats, int n) {
}

int main(int argc, char *argv[]) {

    char *exec_argv[argc + 1];
    exec_argv[0] = "strace";
    for (size_t i = 1; i <= argc; i++) {
        if (i == argc) {
            exec_argv[i] = NULL;
            break;
        }
        exec_argv[i] = argv[i];
    }
    
    //char *exec_argv[] = { "strace", "ls", "-l", NULL, };
    char *exec_envp[] = { "PATH=/bin", NULL, };

    execve("/bin/strace", exec_argv, exec_envp);

    return 0;
}
