#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/wait.h>
#include <unistd.h>
// Feel free to change the data structures generated by AI.

#define MAX_SYSCALLS 1024
#define TOP_N 5

typedef struct {
    char name[64];
    double time;
} syscall_stat;

typedef struct {
    syscall_stat stats[MAX_SYSCALLS];
    int count;
    double total_time;
} syscall_stats;

int parse_strace_line(char *line, char *syscall_name, double *time) {
}

void add_syscall(syscall_stats *stats, const char *name, double time) {
}

void print_top_syscalls(syscall_stats *stats, int n) {
}

int main(int argc, char *argv[]) {

    char *exec_argv[argc + 2];
    exec_argv[0] = "strace";
    exec_argv[1] = "-T";
    for (size_t i = 2; i <= argc + 1; i++) {
        if (i == argc + 1) {
            exec_argv[i] = NULL;
            break;
        }
        exec_argv[i] = argv[i - 1];
    }
    char *exec_envp[] = { "PATH=/bin", NULL, };

    
    pid_t pid = fork();

    if (pid == -1) {
        perror("fork failed"); // 打印错误原因
    } else if (pid == 0) {
        printf("子进程 | PID：%d | 父进程PID：%d\n", getpid(), getppid());
        execve("/bin/strace", exec_argv, exec_envp);
    } else {
        printf("父进程 | PID：%d | 子进程PID：%d\n", getpid(), pid);
    }


    return 0;
}
